from abc import ABC, abstractmethod
from openai import OpenAI
from langchain_openai import ChatOpenAI
from langchain_aws import ChatBedrockConverse
import boto3
import json


class ModelStrategy(ABC):
    """
    Interface for all model strategies.

    This abstract base class defines the structure that all model strategies
    must follow to ensure consistency when generating responses.
    """

    @abstractmethod
    def generate_response(self, prompt: str, **kwargs):
        """
        Generate a response from the model.

        Args:
            prompt (str): Natural language prompt for the model.
            kwargs: Additional parameters to control the model's behavior.

        Returns:
            str: The response generated by the model.
        """
        pass


class OpenAIStrategy(ModelStrategy):
    """
    Implementation of the strategy for OpenAI.

    This strategy interacts with OpenAI's language models (e.g., GPT-4) to generate responses.
    """

    def __init__(self, api_key: str):
        """
        Initialize the OpenAI strategy.

        Args:
            api_key (str): API key for OpenAI authentication.
        """
        self.api_key = api_key

    def generate_response(self, prompt: str, model="gpt-4o-mini", temperature=0.7):
        """
        Generate a response using OpenAI's API.

        Args:
            prompt (str): Natural language prompt for the model.
            model (str): Model name to be used (default: "gpt-4o-mini").
            temperature (float): Sampling temperature for the model (default: 0.7).

        Returns:
            str: The response generated by the model.

        Raises:
            RuntimeError: If the response generation fails.
        """
        try:
            llm = ChatOpenAI(model=model, temperature=temperature, api_key=self.api_key)
            response = llm.invoke(prompt)
            return response.content
        except Exception as e:
            raise RuntimeError(f"Unable to generate ChatCompletion response: {e}")
            return e


class BedrockStrategy(ModelStrategy):
    """
    Implementation of the strategy for AWS Bedrock.

    This strategy interacts with AWS Bedrock's language models to generate responses.
    """

    def __init__(self, aws_access_key: str, aws_secret_access_key: str):
        """
        Initialize the AWS Bedrock strategy.

        Args:
            aws_access_key (str): AWS access key ID.
            aws_secret_access_key (str): AWS secret access key.
        """
        self._aws_access_key = aws_access_key
        self._aws_secret_access_key = aws_secret_access_key

    def generate_response(self, prompt: str, temperature=0.7, max_tokens=200):
        """
        Generate a response using AWS Bedrock.

        Args:
            prompt (str): Natural language prompt for the model.
            temperature (float): Sampling temperature for the model (default: 0.7).
            max_tokens (int): Maximum number of tokens to generate (default: 200).

        Returns:
            str: The response generated by the model.

        Raises:
            RuntimeError: If the response generation fails.
        """
        try:
            llm = ChatBedrockConverse(
                model_id="us.meta.llama3-3-70b-instruct-v1:0",
                aws_access_key_id=self._aws_access_key,
                aws_secret_access_key=self._aws_secret_access_key,
                temperature=temperature,
                max_tokens=max_tokens,
                region_name='us-west-2'
            )
            response = llm.invoke(prompt)
            return response.content
        except Exception as e:
            raise RuntimeError(f"Error generating response with AWS Bedrock: {e}")
            return e


class ModelHandler:
    """
    Manager for model strategies.

    This class is responsible for handling the defined strategy and generating
    responses using the selected model.
    """

    def __init__(self, strategy: ModelStrategy):
        """
        Initialize the model handler with a specific strategy.

        Args:
            strategy (ModelStrategy): The strategy to use for generating responses.
        """
        self.strategy = strategy

    def generate_response(self, prompt: str, **kwargs):
        """
        Generate a response using the defined strategy.

        Args:
            prompt (str): Natural language prompt for the model.
            kwargs: Additional parameters to control the model's behavior.

        Returns:
            str: The response generated by the model.
        """
        return self.strategy.generate_response(prompt, **kwargs)
